config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  resources :tweets, only: [:create, :show] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end
  resources :bookmarks, only: [:index]

  get :dashboard, to: "dashboard#index"
  resources :usernames, only: [:new, :update]  

  get "profile", to: "profile#show", as: "profile"
  put "profile", to: "profile#update"
  resources :hashtags, only: [:index, :show], path: "/explore"
  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :message_thread

  validates :body, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @message_thread = MessageThread.find(params[:message_thread_id])
    @messages = @message_thread.messages
    @user = User.find(params[:other_user_id])

    respond_to do |format|
      format.turbo_stream
    end
  end

  def create
    user = User.find(params[:user_id])
    user_message_thread_ids = MessageThreadsUser.where(user: user).pluck(:message_thread_id)
    my_message_thread_ids = MessageThreadsUser.where(user: current_user).pluck(:message_thread_id)
    common_message_thread_ids = user_message_thread_ids & my_message_thread_ids

    if common_message_thread_ids.empty?
      ActiveRecord::Base::transaction do
        message_thread = MessageThread.create
        user.message_threads << message_thread
        current_user.message_threads << message_thread
        @message =  Message.create(message_params.merge(user: current_user, message_thread: message_thread))
      end
    else
      message_thread = MessageThread.find(common_message_thread_ids.first)
      @message =  Message.create(message_params.merge(user: current_user, message_thread: message_thread))
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/views/messages/_form.html.erb
<div id='message-form'>
  <%= form_with model: Message.new, url: messages_path, local: false, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |f| %>
    <div class='sticky bottom-0 bg-white p-4 border-t border-gray-200'>
      <div class='flex items-center gap-2'>
        <%= hidden_field_tag :user_id, user&.id %>
        <%= f.text_field :body, placeholder: "Type your message here", class: 'flex-1 border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring focus:border-blue-300' %>
        <%= button_tag class: "p-2 text-blue-500 hover:text-blue-700" do %>
          <i class="fa-regular fa-paper-plane text-xl"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div class="<%= message.user == current_user ? 'message-container-current-user' : 'message-container-other-user' %>">
  <div class="flex items-center <%= message.user == current_user ? 'message-flex-current-user' : 'message-flex-other-user' %>">
    <div class="flex items-center justify-center h-10 w-10 rounded-full bg-indigo-500 flex-shrink-0"> A </div>
    
    <div class="flex flex-col">
      <div class="relative <%= message.user == current_user ? 'message-bubble-current-user' : 'message-bubble-other-user' %> text-sm py-2 px-4 shadow rounded-xl">
        <div><%= message.body %></div>
      </div>
      
      <p class="px-4  text-[10px] text-gray-500 <%= message.user == current_user ? 'text-right' : 'text-left' %>">
        <%= message.created_at.strftime("%b %-d, %Y %l:%M %P") %>
      </p>
    </div>
  </div>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages" do %>
  <%= render partial: "messages/message", locals: { message: @message }%>
  <script>
    document.getElementById('messages').scrollIntoView({ behavior: 'smooth', block: 'end' });
  </script>
<% end %>

app/views/messages/index.turbo_stream.erb
<%= turbo_stream.replace "messages" do %>
  <%= render partial: "message_threads/messages", locals: { messages: @messages }%>
<% end %>

<%= turbo_stream.replace "message-form" do %>
 <%= render partial: "messages/form", locals: { user: @user }%>
<% end %>