config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  resources :tweets, only: [:create, :show] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end
  resources :bookmarks, only: [:index]

  get :dashboard, to: "dashboard#index"
  resources :usernames, only: [:new, :update]  

  get "profile", to: "profile#show", as: "profile"
  put "profile", to: "profile#update"
  resources :hashtags, only: [:index, :show], path: "/explore"
  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  HASHTAG_REGEX = /(#\w+)/

  before_save :parse_and_save_hashtags
  after_save :parse_and_save_mentions

  belongs_to :user
  belongs_to :parent_tweet, 
             inverse_of: :reply_tweets, 
             foreign_key: :parent_tweet_id, 
             class_name: "Tweet", 
             optional: true,
             counter_cache: :reply_tweets_count

  has_and_belongs_to_many :hashtags
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user  
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :retweets, dependent: :destroy
  has_many :retweeted_users, through: :retweets, source: :user
  has_many :views
  has_many :viewed_users, through: :views, source: :user
  has_many :reply_tweets, foreign_key: :parent_tweet_id, class_name: "Tweet"
  has_many :mentions, dependent: :destroy
  has_many :mentioned_users, through: :mentions

  validates :body, presence: true, length: { maximum: 1000 }

  private

  def parse_and_save_hashtags
    matches = body.scan(HASHTAG_REGEX)
    return if matches.empty?

    matches.flatten.each do |tag|
      hashtag = Hashtag.find_or_create_by(tag: tag.delete("#"))
      hashtags << hashtag unless hashtags.include?(hashtag)
    end
  end

  def parse_and_save_mentions
    matches = body.scan(/(@\w+)/)
    return if matches.empty?

    matches.flatten.each do |mention|
      mentioned_user = User.find_by(username: mention.delete("@"))
      next if mentioned_user.blank?
      mentions.find_or_create_by(mentioned_user: mentioned_user)
      NotificationService.create_mentioned_me_notification(user: mentioned_user, actor: self.user, tweet: self)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def show
    ViewTweetJob.perform_async(tweet.id, current_user.id)
    @tweet_presenter = TweetPresenter.new(tweet: @tweet, current_user: current_user)
    @reply_tweets_presenters = tweet.reply_tweets
                                    .includes(:user, :liked_users, :bookmarked_users)
                                    .order(created_at: :desc)
                                    .map do |reply_tweet|
      TweetPresenter.new(tweet: reply_tweet, current_user: current_user)
    end
  end

  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to dashboard_path }
        format.turbo_stream
      else
        render :new
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end

  def tweet
    @tweet ||= Tweet.find(params[:id])
  end

  def create_view_record!
    View.create(tweet: tweet, user: current_user)
  end
end

app/views/tweets/_action_links.html.erb
<%= turbo_frame_tag dom_id(tweet_presenter.tweet, :show) do %>
  <div class='flex justify-between mt-4'>
    <div>
      <%= link_to tweet_path(tweet_presenter.tweet), data: { turbo_frame: "_top", turbo_cache: "false" }, class: "relative inline-block hover-link group hover:text-[#74C0FC]" do %>
        <i class="fa-regular fa-comment"></i>
        <span><%= tweet_presenter.reply_tweets_count %></span>
        <span class="hover-text">reply</span>
      <% end %>
    </div>

    <div>
      <%= link_to tweet_presenter.retweet_presenter.url, 
                  data: { "turbo-method": tweet_presenter.retweet_presenter.request }, 
                  class: "relative inline-flex items-center gap-2 hover-link group hover:text-[#74C0FC]" do %>
        <%= tweet_presenter.retweet_presenter.retweet_icon %>
        <span><%= tweet_presenter.retweets_count %></span>
        <span class="hover-text">Retweet</span>
      <% end %>
    </div>
    
    <div>
      <%= link_to tweet_presenter.like_presenter.url, 
                  data: { "turbo-method": tweet_presenter.like_presenter.request }, 
                  class:"relative inline-block hover-link group hover:text-[#74C0FC]" do %>
        <span><%= tweet_presenter.like_presenter.heart_icon %></span>
        <span><%= tweet_presenter.likes_count %></span>
        <span class="hover-text">Like</span>
      <% end %>
    </div>      

    <div>
      <%= link_to tweet_presenter.bookmark_presenter.url, 
          data: { "turbo-method": tweet_presenter.bookmark_presenter.request, turbo_frame: "_top"  }, 
          class:"relative inline-block hover-link group hover:text-[#74C0FC]" do %>
        <span><%= tweet_presenter.bookmark_presenter.bookmark_icon %></span>
        <span>77</span>
        <span class="hover-text">Bookmark</span>
      <% end %>    
    </div>

    <div>
          <%= link_to '#', class: "relative inline-block hover-link group hover:text-[#74C0FC]" do %>
        <i class="fa-solid fa-arrow-up-from-bracket"></i>
      <% end %>
    </div>  
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet_presenter.tweet) do %>
  <div class='flex items-start gap-4 hover:bg-gray-200 rounded-md h-32 p-4'>
    <%= image_tag tweet_presenter.avatar, class: "w-12 h-12 rounded-full", alt: "#{tweet_presenter.display_name}'s avatar" if tweet_presenter.avatar.present? %>
    
    <div class="w-full">
      <span class='font-bold'><%= tweet_presenter.display_name %> </span>
      <span class='text-gray-500'>@<%= tweet_presenter.username %> · <%= tweet_presenter.formatted_created_at %></span>

      <%= link_to tweet_path(tweet_presenter.tweet), data: { turbo_frame: "_top" } do %>
        <p><%= tweet_presenter.body_html.html_safe %></p>
      <% end %>

      <div class='flex justify-between mt-4'>
        <div>
          <%= link_to tweet_path(tweet_presenter.tweet), data: { turbo_frame: "_top", turbo_cache: "false" }, class: "relative inline-block hover-link group hover:text-[#74C0FC]" do %>
            <i class="fa-regular fa-comment"></i>
            <span><%= tweet_presenter.reply_tweets_count %> </span>
            <span class="hover-text">reply</span>
          <% end %>
        </div>

        <div>
          <%= link_to tweet_presenter.retweet_presenter.url, 
                      data: { "turbo-method": tweet_presenter.retweet_presenter.request }, 
                      class: "relative inline-flex items-center gap-2 hover-link group hover:text-[#74C0FC]" do %>
            <%= tweet_presenter.retweet_presenter.retweet_icon %>
            <span><%= tweet_presenter.retweets_count %></span>
            <span class="hover-text">Retweet</span>
          <% end %>
        </div>
        
        <div>
          <%= link_to tweet_presenter.like_presenter.url, 
                      data: { "turbo-method": tweet_presenter.like_presenter.request }, 
                      class:"relative inline-block hover-link group hover:text-[#74C0FC]" do %>
            <span><%= tweet_presenter.like_presenter.heart_icon %></span>
            <span><%= tweet_presenter.likes_count %></span>
            <span class="hover-text">Like</span>
          <% end %>
        </div>      

        <div>
          <%= link_to '#', class: "relative inline-block hover-link group hover:text-[#74C0FC]" do %>
            <i class="fa-solid fa-chart-column"></i>
            <span><%= tweet_presenter.views_count %></span>
            <span class="hover-text">View</span>
          <% end %>
        </div>

        <div class="flex gap-4">
          <%= link_to tweet_presenter.bookmark_presenter.url, 
              data: { "turbo-method": tweet_presenter.bookmark_presenter.request, turbo_frame: "_top"  }, 
              class:"relative inline-block hover-link group hover:text-[#74C0FC]" do %>
            <span><%= tweet_presenter.bookmark_presenter.bookmark_icon %></span>
            <span class="hover-text">Bookmark</span>
          <% end %>                                             

          <%= link_to '#', class: "relative inline-block hover-link group hover:text-[#74C0FC]" do %>
            <i class="fa-solid fa-arrow-up-from-bracket"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(tweet: @tweet.reload, current_user: current_user) } %>
<% end %>

<%= turbo_stream.replace "new_post" do %>
  <%= turbo_frame_tag "new_post" do %>    
    <%= form_with model: Tweet.new, url: tweets_path, method: :post, data: { turbo_frame: "new_post" } do |f| %>
      <div class="mb-4">
        <%= f.text_area :body, placeholder: "What's happening?", class: "w-full border-0  p-4 text-gray-700 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>

      <div class="flex items-center justify-end ">
        <%= f.submit "Tweet", class: "w-24 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  <% end %>
<% end %>

<%= turbo_stream.replace 'new_tweet_modal' do %>
  <%= render partial: 'layouts/modal', locals: { tweet: @tweet } %>
<% end %>

app/views/tweets/show.html.erb
<div class='w-full bg-white rounded-lg'>
  <div class="flex justify-start items-center ">
    <%= link_to :back, class: 'back-button', data: { controller: 'back', action: 'click->back#goBack' } do %>
      <%= image_tag 'back_btn.svg', alt: 'Back', class: 'w-5 h-5' %>
    <% end %>
    <h2 class="text-xl font-bold ml-2">Post</h2>
  </div>

  <div class='flex gap-4 mt-4'>
    <%= image_tag @tweet_presenter.avatar, class: "w-12 h-12 rounded-full", alt: "#{@tweet_presenter.display_name}'s avatar" if @tweet_presenter.avatar.present? %>
    
    
    
    <div>
      <p class='font-bold'><%= @tweet_presenter.display_name %> </p>
      <p class='text-gray-500'>@<%= @tweet_presenter.username %></p>
    </div>
  </div>

  <div class='mt-4 text-2xl'><%= @tweet_presenter.body_html.html_safe %></div>

  <div class="my-4">
    <span ><%= @tweet_presenter.formatted_time %></span>
    <span>·</span>
    <span><%= @tweet_presenter.formatted_full_date %></span>
    <span>·</span>
    <span><%= @tweet_presenter.views_count %> Views</span>             
  </div>

  <hr>

  <div class='m-4'>
    <%= render partial: "tweets/action_links", locals: { tweet_presenter: @tweet_presenter } %>
  </div>
  
  <hr>

  <div class='flex items-start gap-4 rounded-md p-4'>
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, class: "w-12 h-12 rounded-full" %>
    <% else %>
      <%= image_tag "user-profile.svg", class: "w-12 h-12 rounded-full" %>
    <% end %>
    
    <div class="w-full">
      <%= turbo_frame_tag "tweet_reply_form" do %>
        <%= render partial: "shared/tweet_form", locals: { 
                                                  submit_form_path: tweet_reply_tweets_path(@tweet_presenter.tweet),
                                                  button_label: "Reply", 
                                                  placeholder_label: "Post your reply" } %>
      <% end %>
    </div>
  </div>

  <hr>

  
  <div id='reply_tweets'>
    <%= render partial: "tweets/tweet", collection:  @reply_tweets_presenters, as: :tweet_presenter %>
  
  </div>

</div>