config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  resources :tweets, only: [:create, :show] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: [:create]
  end
  resources :bookmarks, only: [:index]

  get :dashboard, to: "dashboard#index"
  resources :usernames, only: [:new, :update]  

  get "profile", to: "profile#show", as: "profile"
  put "profile", to: "profile#update"
  resources :hashtags, only: [:index, :show], path: "/explore"
  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end
  resources :messages, only: :create

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_save  :set_display_name, if: -> { username.present? && display_name.blank? }

  has_one_attached :avatar

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_tweets, through: :bookmarks, source: :tweet
  has_many :retweets, dependent: :destroy
  has_many :retweeted_tweets, through: :retweets, source: :tweet
  has_many :views
  has_many :viewed_tweets, through: :views, source: :tweet
  has_many :followings, dependent: :destroy
  has_many :following_user, through: :followings, source: :following_user
  has_many :reverse_followings, foreign_key: :following_user_id, class_name: "Following"
  has_many :followers, through: :reverse_followings, source: :user
  has_many :notifications,  dependent: :destroy

  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :message_threads

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true

  def set_display_name
    self.display_name = username.humanize
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    redirect_to profile_path if params[:id].to_i == current_user.id
    @user = User.find(params[:id])
    @tweet_presenters = @user.tweets.map do |tweet|
      TweetPresenter.new(tweet: tweet, current_user: @user)
    end
  end
end

app/views/users/_follow_botton.html.erb
<%= turbo_frame_tag "follow-unfollow"  do %>
  <% if user.followers.include?(current_user) %>
    <%= link_to "Unfollow", user_following_path(user, current_user.followings.find_by(following_user_id: user)), 
                            data: { "turbo-method": :delete },
                            class: "rounded-full px-4 py-2 border  font-bold text-white bg-[#74C0FC] hover:bg-[#fff] hover:border-[#74C0FC] howver:bg-gray-200 hover:text-black " %>
  <% else %>
    <%= link_to "Follow",  user_followings_path(current_user, following_user_id: user.id),
                            data: { "turbo-method": :post },
                            class: "rounded-full px-4 py-2 border border-[#74C0FC] text-[#74C0FC] font-bold hover:text-white hover:bg-[#74C0FC]" %>
  <% end %>
<% end %>

app/views/users/show.html.erb
 <%= turbo_frame_tag "profile" do %> 
  <div class='w-full  h-3000px'>
    <div class="flex justify-start items-center m-4 ">
      <%= link_to :back, class: 'back-button', data: { controller: 'back', action: 'click->back#goBack' } do %>
        <%= image_tag 'back_btn.svg', alt: 'Back', class: 'w-5 h-5' %>
      <% end %>
      <div class='ml-8'>
        <h2 class="text-xl font-bold "><%= @user.display_name %> </h2>
        <p class="text-s "><%= @user.tweets.size %> Post </p>
      </div>
    </div>

    <div class='flex justify-between items-center'>
      <% if @user.avatar.present? %>
        <%= image_tag @user.avatar, class: "w-24 h-24 rounded-full border-2 border-gray p-1" %>
      <% else %>
        <%= image_tag "user-profile.svg", class: "w-24 h-24 rounded-full border-2 border-gray  p-1" %>
      <% end %>
    
      <% if controller_name == "profile" %>
        <%= profile_modal_button 'Set up profile' %>
      <% else %>
        <div class='flex justify-center items-center gap-3'>
          <%= link_to message_threads_path(user_id: @user.id), data: { controller: "messages", action: "", turbo: "false" } do %>
            <div class='rounded-full px-2 py-1 border border-[#74C0FC] text-black font-bold hover:text-white hover:bg-[#74C0FC]'>
              <i class="fa-regular text-3xl fa-envelope"></i>
            </div>
          <% end %>
          
          <div class=''>
            <%= render partial: "users/follow_botton", locals: { user: @user, current_user: current_user } %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="mt-8">
      <h2><%= @user.display_name %> </h2>
      <p>@<%= @user.display_name %> </p>

      <div class='mt-4'>
        <i class="fa-regular fa-calendar-days mt-4"></i> Joined August 2024      
      </div>

      <%= render partial: "shared/follower_and_following_count_frame", locals: { user: @user } %>
    </div>
  </div>

  <hr class="my-4">

  <div id='tweets'>
    <%= render partial: "tweets/tweet", collection: @tweet_presenters, as: :tweet_presenter %>
  </div>

  <%= render "profile/profile_modal" %>
<% end %>